spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://localhost:3306/cisdi_smartmem?useUnicode=true&characterEncoding=utf-8
    username: root
    password: root


custom:
  datasource:
    names: ds1,ds2,ds3

    ds1:
      url: jdbc:mysql://localhost:3306/ds1
      username: root
      password: root
      driver-class-name: org.gjt.mm.mysql.Driver
    ds2:
      url: jdbc:mysql://localhost:3306/ds2
      username: root
      password: root
      driver-class-name: org.gjt.mm.mysql.Driver
    ds3:
      url: jdbc:mysql://localhost:3306/ds3
      username: root
      password: root
      driver-class-name: org.gjt.mm.mysql.Driver